#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter

#
# Complete the 'isValid' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def isValid(s):
    # Write your code here
    x=Counter(s)
    count=x.values()
    frequency=len(set(count))
    if frequency==1:
        return "YES"
    if frequency>2:
        return "NO"
    min_val=min(count)
    keys_with_min_value = [key for key, value in x.items() if value == min_val]
    max_val=max(count)
    keys_with_max_value = [key for key, value in x.items() if value == max_val]
    if len(keys_with_min_value)==1 and len(keys_with_max_value)>=1 and min_val==1:
        return "YES"
    if len(keys_with_min_value)>=1 and len(keys_with_max_value)==1 and max_val-1==min_val:
        
        return "YES"
    return "NO"
    
        
        
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = isValid(s)

    fptr.write(result + '\n')

    fptr.close()
